package httptransport

import (
	"bytes"
	"embed"
	"fmt"
	"io/fs"
	"net/http"
	"time"
)

// documentationFiles contains the pinned Swagger UI distribution and the
// OpenAPI document generated by buf before the application is compiled.
//
//go:embed docs
var documentationFiles embed.FS

func withDocumentation(gateway http.Handler, enabled bool) (http.Handler, error) {
	if !enabled {
		return gateway, nil
	}

	docs, err := fs.Sub(documentationFiles, "docs")
	if err != nil {
		return nil, fmt.Errorf("open embedded documentation: %w", err)
	}
	openAPI, err := fs.ReadFile(docs, "go-foundation.swagger.json")
	if err != nil {
		return nil, fmt.Errorf("read embedded OpenAPI document: %w", err)
	}

	staticFiles := http.StripPrefix("/docs/", http.FileServer(http.FS(docs)))
	mux := http.NewServeMux()
	mux.Handle("/", gateway)
	mux.HandleFunc("GET /docs", func(w http.ResponseWriter, r *http.Request) {
		http.Redirect(w, r, "/docs/", http.StatusPermanentRedirect)
	})
	mux.Handle("GET /docs/", cacheDocumentation(staticFiles))
	mux.HandleFunc("GET /openapi.json", func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Cache-Control", "no-store")
		w.Header().Set("Content-Type", "application/json")
		w.Header().Set("X-Content-Type-Options", "nosniff")
		http.ServeContent(w, r, "openapi.json", time.Time{}, bytes.NewReader(openAPI))
	})
	return mux, nil
}

func cacheDocumentation(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Cache-Control", "public, max-age=86400")
		w.Header().Set("Referrer-Policy", "no-referrer")
		w.Header().Set("X-Content-Type-Options", "nosniff")
		next.ServeHTTP(w, r)
	})
}
